ProyectoRestaurante_templateHome/ProyectoRestaurante/urls.py
from django.contrib import admin
from django.urls import path, include
from mesas import views as mesas_views  # Alias para las vistas de mesas
from menu import views as menu_views  # Alias para las vistas de menú
from estadisticas import views as estadisticas_views
from menu.views import categories_view, meals_view, convertir_divisa
from pedidos import views as pedidos_views  # Alias para las vistas de pedidos

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mesas_views.home, name='home'),  # Usando alias para vistas de mesas

    path('login/', mesas_views.login_view, name='login'),
    path('register/', mesas_views.register, name='register'),
    path('logout/', mesas_views.logout_view, name='logout'),

    path('menu/', menu_views.gestionar_menu, name='gestionar_menu'),  # Usando alias para vistas de menú
    path('estadistica/', estadisticas_views.estadistica, name='estadistica'),
    path('estadisticas/meseros/', estadisticas_views.estadisticas_meseros, name='estadisticas_meseros'),
    path('estadisticas/mesas/', estadisticas_views.estadisticas_mesas, name='estadisticas_mesas'),
    path('estadisticas/productos/', estadisticas_views.estadisticas_productos, name='estadisticas_productos'),
    path('estadisticas/ventastotales/', estadisticas_views.ventas_totales, name='ventas_totales'),
    path('estadisticas/reportes/', estadisticas_views.reportes, name='reportes'),
    path('estadisticas/reporte_pdf/', estadisticas_views.reporte_pdf, name='reporte_pdf'),

    path('homeAdmin/', mesas_views.homeAdmin, name='homeAdmin'),
    path('listar_mesas/', mesas_views.listar_mesas.as_view(), name='listar_mesas'),
    path('editar_mesas/<int:pk>/', mesas_views.edicion_mesas.as_view(), name='editar_mesas'),
    path('reservar/', mesas_views.crear_reserva, name='crear_reserva'),
    path('reserva_exito/', mesas_views.reserva_exito, name='reserva_exito'),
    path('eliminar_reserva/<int:pk>/', mesas_views.eliminar_reserva, name='eliminar_reserva'),
    path('crear_mesa/', mesas_views.crear_mesa.as_view(), name='crear_mesa'),
    path('eliminar_mesa/<int:pk>/', mesas_views.eliminar_mesa, name='eliminar_mesa'),

    path('listar_menu/', menu_views.listar_menu.as_view(), name='listar_menu'),
    path('editar_menu/<int:pk>/', menu_views.edicion_menu.as_view(), name='editar_menu'),
    path('crear_menu/', menu_views.crear_menu, name='crear_menu'),
    path('menu/<int:pk>/eliminar/', menu_views.eliminar_menu, name='eliminar_menu'),
    path('menu/<int:pk>/categorias/', menu_views.listar_categorias.as_view(), name='listar_categorias'),
    path('categorias/<int:pk>/editar/', menu_views.edicion_categoria.as_view(), name='editar_categoria'),
    path('categorias/crear/', menu_views.crear_categoria, name='crear_categoria'),
    path('categorias/<int:pk>/eliminar/', menu_views.eliminar_categoria, name='eliminar_categoria'),
    path('categorias/<int:pk>/productos/', menu_views.listar_productos.as_view(), name='listar_productos'),
    path('productos/<int:pk>/editar/', menu_views.edicion_producto.as_view(), name='editar_producto'),
    path('productos/crear/', menu_views.crear_producto, name='crear_producto'),
    path('productos/<int:pk>/eliminar/', menu_views.eliminar_producto, name='eliminar_producto'),
    path('menus/', include('menu.urls')),
    path('convertir/', convertir_divisa, name='convertir_divisa'),
    path('listar_reservas/', mesas_views.listar_reservas, name='listar_reservas'),
    path('reservas/crear/', mesas_views.crear_reserva, name='crear_reserva'),
    path('pedidos/', pedidos_views.gestionar_pedidos, name='gestionar_pedidos'),  # Añadido para pedidos
]

ProyectoRestaurante_templateHome/menu/urls.py
from django.urls import path
from .views import categories_view, meals_view, meal_detail_view

urlpatterns = [
    path('categorias/', categories_view, name='categories'),
    path('categorias/<str:category_name>/', meals_view, name='meals_by_category'),
    path('menus/<str:meal_id>/', meal_detail_view, name='meal_detail'),
]

ProyectoRestaurante_templateHome/menu/models.py
from django.db import models
from abc import ABC, abstractmethod
from typing import List, Dict, Any

class Menu(models.Model):
    nombre = models.CharField(max_length=50)
    estado = models.BooleanField()

    def __str__(self):
        return self.nombre

    def activar_menu(self) -> None:
        self.estado = True
        self.save()

    def desactivar_menu(self) -> None:
        self.estado = False
        self.save()


class Categoria(models.Model):
    nombre = models.CharField(max_length=50)
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE, related_name='categorias')

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=255)
    precio = models.FloatField(default=0)
    disponibilidad = models.BooleanField()
    cantidad_vendida = models.IntegerField(default=0)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, related_name='productos')

    def actualizar_precio(self, nuevo_precio):
        self.precio = nuevo_precio
        self.save()

    def __str__(self):
        return self.nombre

    def cambiar_disponibilidad(self, disponible: bool) -> None:
        self.disponibilidad = disponible
        self.save()


class IMenu(ABC):

    @abstractmethod
    def agregar_producto(self, categoria_id: int, producto_data: Dict[str, Any]) -> Producto:
        pass

    @abstractmethod
    def eliminar_producto(self, producto_id: int) -> None:
        pass

    @abstractmethod
    def agregar_categoria(self, menu_id: int, nombre_categoria: str) -> Categoria:
        pass

    @abstractmethod
    def eliminar_categoria(self, categoria_id: int) -> None:
        pass

    @abstractmethod
    def modificar_categoria(self, categoria_id: int, nuevo_nombre: str) -> None:
        pass

    @abstractmethod
    def modificar_producto(self, producto_id: int, producto_data: Dict[str, Any]) -> None:
        pass

    @abstractmethod
    def buscar_categoria(self, nombre: str) -> List[Categoria]:
        pass

    @abstractmethod
    def buscar_producto(self, nombre: str) -> List[Producto]:
        pass

    @abstractmethod
    def mostrar_menu(self, menu_id: int) -> Dict[str, Any]:
        pass


class MenuService(IMenu):

    def agregar_producto(self, categoria_id: int, producto_data: Dict[str, Any]) -> Producto:
        categoria = Categoria.objects.get(id=categoria_id)
        if Producto.objects.filter(nombre=producto_data["nombre"], categoria=categoria).exists():
            raise ValueError(f"El producto '{producto_data['nombre']}' ya existe en esta categoría.")

        producto = Producto.objects.create(
            nombre=producto_data["nombre"],
            descripcion=producto_data["descripcion"],
            precio=producto_data["precio"],
            disponibilidad=producto_data["disponibilidad"],
            categoria=categoria
        )
        return producto

    def eliminar_producto(self, producto_id: int) -> None:
        producto = Producto.objects.filter(id=producto_id).first()
        if not producto:
            raise ValueError(f"Producto con ID {producto_id} no encontrado.")

        producto.delete()

    def agregar_categoria(self, menu_id: int, nombre_categoria: str) -> Categoria:
        menu = Menu.objects.get(id=menu_id)
        categoria = Categoria.objects.create(nombre=nombre_categoria, menu=menu)
        return categoria

    def eliminar_categoria(self, categoria_id: int) -> None:
        categoria = Categoria.objects.filter(id=categoria_id).first()
        if not categoria:
            raise ValueError(f"Categoría con ID {categoria_id} no encontrada.")

        categoria.delete()

    def modificar_categoria(self, categoria_id: int, nuevo_nombre: str) -> None:
        categoria = Categoria.objects.filter(id=categoria_id).first()
        if not categoria:
            raise ValueError(f"Categoría con ID {categoria_id} no encontrada.")

        categoria.nombre = nuevo_nombre
        categoria.save()

    def modificar_producto(self, producto_id: int, producto_data: Dict[str, Any]) -> None:
        producto = Producto.objects.filter(id=producto_id).first()
        if not producto:
            raise ValueError(f"Producto con ID {producto_id} no encontrado.")

        producto.nombre = producto_data["nombre"]
        producto.descripcion = producto_data["descripcion"]
        producto.precio = producto_data["precio"]
        producto.disponibilidad = producto_data["disponibilidad"]
        producto.save()

    def buscar_categoria(self, nombre: str) -> List[Categoria]:
        return list(Categoria.objects.filter(nombre__icontains=nombre))

    def buscar_producto(self, nombre: str) -> List[Producto]:
        return list(Producto.objects.filter(nombre__icontains=nombre))

    def mostrar_menu(self, menu_id: int) -> Dict[str, Any]:
        menu = Menu.objects.get(id=menu_id)
        categorias = Categoria.objects.filter(menu=menu)
        return {
            "menu": menu.nombre,
            "estado": menu.estado,
            "categorias": [
                {
                    "nombre": cat.nombre,
                    "productos": list(cat.productos.values("nombre", "descripcion", "precio", "disponibilidad"))
                } for cat in categorias
            ]
        }

    def activar_producto(self, producto_id: int) -> None:
        producto = Producto.objects.get(id=producto_id)
        producto.disponibilidad = True
        producto.save()

    def desactivar_producto(self, producto_id: int) -> None:
        producto = Producto.objects.get(id=producto_id)
        producto.disponibilidad = False
        producto.save()

    def mostrar_productos_por_categoria(self, categoria_id: int) -> List[Dict[str, Any]]:
        categoria = Categoria.objects.get(id=categoria_id)
        productos = Producto.objects.filter(categoria=categoria)
        return list(productos.values("id", "nombre", "descripcion", "precio", "disponibilidad"))

    def buscar_producto_por_precio(self, min_precio: float, max_precio: float) -> List[Producto]:
        return list(Producto.objects.filter(precio__gte=min_precio, precio__lte=max_precio))

ProyectoRestaurante_templateHome/menu/forms.py
# menu/forms.py
from django import forms
from .models import Menu, Categoria, Producto

class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = ['nombre', 'estado']

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['nombre', 'menu']

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['nombre', 'descripcion', 'precio', 'disponibilidad', 'categoria']

class ConversionForm(forms.Form):
    MONEDAS = [
        ('USD', 'Dólar Estadounidense'),
        ('EUR', 'Euro'),
        ('COP', 'Peso Colombiano'),
        ('PEN', 'Sol Peruano'),
        ('VES', 'Bolívar Venezolano'),
        ('BRL', 'Real Brasileño'),
        ('ARS', 'Peso Argentino'),
        ('CLP', 'Peso Chileno'),
        ('PAB', 'Balboa Panameño'),
        ('UYU', 'Peso Uruguayo'),
        ('CAD', 'Dólar Canadiense'),
        ('HNL', 'Lempira Hondureño'),
        ('KRW', 'Won Surcoreano'),
        ('JPY', 'Yen Japonés'),
        ('CNY', 'Yuan Chino (Renminbi)'),
        # En este apartado podemos agregar más monedas
    ]

    moneda_origen = forms.ChoiceField(choices=MONEDAS, label='Moneda de Origen')
    moneda_destino = forms.ChoiceField(choices=MONEDAS, label='Moneda de Destino')
    monto = forms.DecimalField(min_value=0, label='Monto a Convertir')

ProyectoRestaurante_templateHome/templates/AdminIndividual/menu/crear_categoria.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pedidos - Restaurante Michu</title>
    <link rel="stylesheet" href="{% static 'css/pedidos.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&family=Playfair+Display:wght@400;700&display=swap" rel="stylesheet">
</head>
<body>
    <div class="banner"></div>
    <header>
        <div class="logo">
            <img src="{% static 'image/Logo.jpg.png' %}" alt="Logo Restaurante Michu">
            <span class="restaurant-name">Restaurante Michu</span>
        </div>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">INICIO</a></li>
                <li><a href="{% url 'gestionar_menu' %}">MENÚ</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'listar_reservas' %}">RESERVACIONES</a></li>
                    <li><a href="{% url 'estadistica' %}">ESTADISTICAS</a></li>
                    <li><a href="{% url 'listar_mesas' %}">MESAS</a></li>
                    <li><a href="{% url 'gestionar_pedidos' %}">PEDIDOS</a></li>
                    <li><a href="{% url 'convertir_divisa' %}">MONEDAS</a></li>
                    <li><a href="{% url 'logout' %}">CERRAR SESIÓN</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">INICIAR SESIÓN</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>

    <div class="form-container">
        <h1>Nueva Categoria</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn">Crear Categoria</button>
        </form>
    </div>
    
    <div class="btn-container">
        <a href="{% url 'listar_menu' %}" class="btn">Volver a Menús</a>
    </div>

</body>
</html>

ProyectoRestaurante_templateHome/templates/AdminIndividual/menu/crear_menu.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Reservas</title>
    <link rel="stylesheet" href="{% static 'css/pedidos.css' %}?v=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&family=Playfair+Display:wght@400;700&display=swap" rel="stylesheet">
</head>
<body>
    <div class="banner"></div>
    <header>
        <div class="logo">
            <img src="{% static 'image/Logo.jpg.png' %}" alt="Logo Restaurante Michu">
            <span class="restaurant-name">Restaurante Michu</span>
        </div>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">INICIO</a></li>
                <li><a href="{% url 'gestionar_menu' %}">MENÚ</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'listar_reservas' %}">RESERVACIONES</a></li>
                    <li><a href="{% url 'estadistica' %}">ESTADISTICAS</a></li>
                    <li><a href="{% url 'listar_mesas' %}">MESAS</a></li>
                    <li><a href="{% url 'gestionar_pedidos' %}">PEDIDOS</a></li>
                    <li><a href="{% url 'convertir_divisa' %}">MONEDAS</a></li>
                    <li><a href="{% url 'logout' %}">CERRAR SESIÓN</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">INICIAR SESIÓN</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>

 <main>
        <section class="hero">
            <img src="{% static 'image/pedidos.jpg' %}" alt="Imagen de pedidos" class="hero-image">
            <h1>Cree un Menu</h1>
            <div class="form-container">
                <div class="form-column">
                    <form method="POST">
                        {% csrf_token %}

                        <div class="form-group">
                            <label for="id_nombre">Nombre</label>
                            {{ form.nombre }}
                        </div>

                        <div class="form-group">
                            <label for="id_estado">Estado</label>
                            {{ form.estado }}
                        </div>

                        <button type="submit" name="crear_menu">Crear Menu</button>
                    </form>
                </div>
            </div>
        </section>
    </main>


</body>
</html>

ProyectoRestaurante_templateHome/templates/AdminIndividual/menu/crear_productos.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Generar Categoria</title>
    <link rel="stylesheet" href="{% static 'css/formularios.css' %}">
</head>
<body>
    <div class="banner"></div>
    <header>
        <div class="logo">
            <img src="{% static 'image/Logo.jpg.png' %}" alt="Logo Restaurante Michu">
            <span class="restaurant-name">Restaurante Michu</span>
        </div>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">INICIO</a></li>
                <li><a href="{% url 'gestionar_menu' %}">MENÚ</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'listar_reservas' %}">RESERVACIONES</a></li>
                    <li><a href="{% url 'estadistica' %}">ESTADISTICAS</a></li>
                    <li><a href="{% url 'listar_mesas' %}">MESAS</a></li>
                    <li><a href="{% url 'gestionar_pedidos' %}">PEDIDOS</a></li>
                    <li><a href="{% url 'convertir_divisa' %}">MONEDAS</a></li>
                    <li><a href="{% url 'logout' %}">CERRAR SESIÓN</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">INICIAR SESIÓN</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>

    <div class="form-container">
        <h1>Nueva Producto</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn">Crear Producto</button>
        </form>
    </div>
    
    <div class="btn-container">
        <a href="{% url 'listar_menu' %}" class="btn">Volver a Menús</a>
    </div>

</body>
</html>

ProyectoRestaurante_templateHome/templates/AdminIndividual/menu/editar_categoria.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Mesas</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&family=Playfair+Display:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/pedidos.css' %}?v=2">
</head>
<body>
<header>
        <div class="logo">
            <img src="{% static 'image/Logo.jpg.png' %}" alt="Logo Restaurante Michu">
            <span class="restaurant-name">Restaurante Michu</span>
        </div>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">INICIO</a></li>
                <li><a href="{% url 'gestionar_menu' %}">MENÚ</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'listar_reservas' %}">RESERVACIONES</a></li>
                    <li><a href="{% url 'estadistica' %}">ESTADISTICAS</a></li>
                    <li><a href="{% url 'listar_mesas' %}">MESAS</a></li>
                    <li><a href="{% url 'gestionar_pedidos' %}">PEDIDOS</a></li>
                    <li><a href="{% url 'convertir_divisa' %}">MONEDAS</a></li>
                    <li><a href="{% url 'logout' %}">CERRAR SESIÓN</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">INICIAR SESIÓN</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        <h1>Editar Categoria</h1>
        <div class="form-container">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn">Guardar Cambios</button>
            </form>
            <div class="button">
            <a href="/listar_menu/" >Volver a Menus</a>
            </div>
        </div>
    </main>

</body>
</html>

ProyectoRestaurante_templateHome/templates/AdminIndividual/menu/editar_menu.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Mesas</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&family=Playfair+Display:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/formularios.css' %}?v=2">
</head>
<body>
<header>
        <div class="logo">
            <img src="{% static 'image/Logo.jpg.png' %}" alt="Logo Restaurante Michu">
            <span class="restaurant-name">Restaurante Michu</span>
        </div>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">INICIO</a></li>
                <li><a href="{% url 'gestionar_menu' %}">MENÚ</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'listar_reservas' %}">RESERVACIONES</a></li>
                    <li><a href="{% url 'estadistica' %}">ESTADISTICAS</a></li>
                    <li><a href="{% url 'listar_mesas' %}">MESAS</a></li>
                    <li><a href="{% url 'gestionar_pedidos' %}">PEDIDOS</a></li>
                    <li><a href="{% url 'convertir_divisa' %}">MONEDAS</a></li>
                    <li><a href="{% url 'logout' %}">CERRAR SESIÓN</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">INICIAR SESIÓN</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        <h1>Editar Menu</h1>
        <div class="form-container">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn">Guardar Cambios</button>
            </form>
            <div class="button">
            <a href="/listar_menu/" >Volver a Menus</a>
            </div>
        </div>
    </main>

</body>
</html>

ProyectoRestaurante_templateHome/templates/AdminIndividual/menu/editar_productos.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Mesas</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&family=Playfair+Display:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/formularios.css' %}?v=2">
</head>
<body>
<header>
        <div class="logo">
            <img src="{% static 'image/Logo.jpg.png' %}" alt="Logo Restaurante Michu">
            <span class="restaurant-name">Restaurante Michu</span>
        </div>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">INICIO</a></li>
                <li><a href="{% url 'gestionar_menu' %}">MENÚ</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'listar_reservas' %}">RESERVACIONES</a></li>
                    <li><a href="{% url 'estadistica' %}">ESTADISTICAS</a></li>
                    <li><a href="{% url 'listar_mesas' %}">MESAS</a></li>
                    <li><a href="{% url 'gestionar_pedidos' %}">PEDIDOS</a></li>
                    <li><a href="{% url 'convertir_divisa' %}">MONEDAS</a></li>
                    <li><a href="{% url 'logout' %}">CERRAR SESIÓN</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">INICIAR SESIÓN</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        <h1>Editar Productos</h1>
        <div class="form-container">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn">Guardar Cambios</button>
            </form>
            <div class="button">
            <a href="/listar_menu/" >Volver a Menus</a>
            </div>
        </div>
    </main>

</body>
</html>

ProyectoRestaurante_templateHome/templates/AdminIndividual/menu/gestionar_menu.html
{% load static %}  <!-- Cargar la etiqueta static de Django -->
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Menú - Restaurante Michu</title>
    <!-- Carga de archivos CSS -->
    <link rel="stylesheet" href="{% static 'css/gestion_menu.css' %}?v=1.0"|>
    <!-- Fuente de Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&family=Playfair+Display:wght@400;700&display=swap" rel="stylesheet">
</head>
<body>
    <div class="banner"></div>
    <header>
        <div class="logo">
            <img src="{% static 'image/Logo.jpg.png' %}" alt="Logo Restaurante Michu">
            <span class="restaurant-name">Restaurante Michu</span>
        </div>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">INICIO</a></li>
                <li><a href="{% url 'gestionar_menu' %}">MENÚ</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'listar_reservas' %}">RESERVACIONES</a></li>
                    <li><a href="{% url 'estadistica' %}">ESTADISTICAS</a></li>
                    <li><a href="{% url 'listar_mesas' %}">MESAS</a></li>
                    <li><a href="{% url 'gestionar_pedidos' %}">PEDIDOS</a></li>
                    <li><a href="{% url 'convertir_divisa' %}">MONEDAS</a></li>
                    <li><a href="{% url 'logout' %}">CERRAR SESIÓN</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">INICIAR SESIÓN</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>

    <!-- Sección Hero con la imagen de fondo -->
    <main>
        <section class="hero">
            <img src="{% static 'image/Menu.jpg' %}" alt="Imagen del Menú" class="hero-image">
            <h1>Descubre Nuestro Menú Exclusivo</h1>
            <p>Elige entre nuestras deliciosas opciones, elaboradas con ingredientes frescos y de alta calidad.</p>
            <a href="{% url 'categories' %}">
            <button>VER MENU</button>
        </section>
    </main>

    <!-- Carga de archivos JS -->
    <script src="{% static 'js/gestion_menu.js' %}"></script>
</body>
</html>