ProyectoRestaurante_templateHome/ProyectoRestaurante/urls.py
from django.contrib import admin
from django.urls import path, include
from mesas import views as mesas_views  # Alias para las vistas de mesas
from menu import views as menu_views  # Alias para las vistas de menú
from estadisticas import views as estadisticas_views
from menu.views import categories_view, meals_view, convertir_divisa
from pedidos import views as pedidos_views  # Alias para las vistas de pedidos

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mesas_views.home, name='home'),  # Usando alias para vistas de mesas

    path('login/', mesas_views.login_view, name='login'),
    path('register/', mesas_views.register, name='register'),
    path('logout/', mesas_views.logout_view, name='logout'),

    path('menu/', menu_views.gestionar_menu, name='gestionar_menu'),  # Usando alias para vistas de menú
    path('estadistica/', estadisticas_views.estadistica, name='estadistica'),
    path('estadisticas/meseros/', estadisticas_views.estadisticas_meseros, name='estadisticas_meseros'),
    path('estadisticas/mesas/', estadisticas_views.estadisticas_mesas, name='estadisticas_mesas'),
    path('estadisticas/productos/', estadisticas_views.estadisticas_productos, name='estadisticas_productos'),
    path('estadisticas/ventastotales/', estadisticas_views.ventas_totales, name='ventas_totales'),
    path('estadisticas/reportes/', estadisticas_views.reportes, name='reportes'),
    path('estadisticas/reporte_pdf/', estadisticas_views.reporte_pdf, name='reporte_pdf'),

    path('homeAdmin/', mesas_views.homeAdmin, name='homeAdmin'),
    path('listar_mesas/', mesas_views.listar_mesas.as_view(), name='listar_mesas'),
    path('editar_mesas/<int:pk>/', mesas_views.edicion_mesas.as_view(), name='editar_mesas'),
    path('reservar/', mesas_views.crear_reserva, name='crear_reserva'),
    path('reserva_exito/', mesas_views.reserva_exito, name='reserva_exito'),
    path('eliminar_reserva/<int:pk>/', mesas_views.eliminar_reserva, name='eliminar_reserva'),
    path('crear_mesa/', mesas_views.crear_mesa.as_view(), name='crear_mesa'),
    path('eliminar_mesa/<int:pk>/', mesas_views.eliminar_mesa, name='eliminar_mesa'),

    path('listar_menu/', menu_views.listar_menu.as_view(), name='listar_menu'),
    path('editar_menu/<int:pk>/', menu_views.edicion_menu.as_view(), name='editar_menu'),
    path('crear_menu/', menu_views.crear_menu, name='crear_menu'),
    path('menu/<int:pk>/eliminar/', menu_views.eliminar_menu, name='eliminar_menu'),
    path('menu/<int:pk>/categorias/', menu_views.listar_categorias.as_view(), name='listar_categorias'),
    path('categorias/<int:pk>/editar/', menu_views.edicion_categoria.as_view(), name='editar_categoria'),
    path('categorias/crear/', menu_views.crear_categoria, name='crear_categoria'),
    path('categorias/<int:pk>/eliminar/', menu_views.eliminar_categoria, name='eliminar_categoria'),
    path('categorias/<int:pk>/productos/', menu_views.listar_productos.as_view(), name='listar_productos'),
    path('productos/<int:pk>/editar/', menu_views.edicion_producto.as_view(), name='editar_producto'),
    path('productos/crear/', menu_views.crear_producto, name='crear_producto'),
    path('productos/<int:pk>/eliminar/', menu_views.eliminar_producto, name='eliminar_producto'),
    path('menus/', include('menu.urls')),
    path('convertir/', convertir_divisa, name='convertir_divisa'),
    path('listar_reservas/', mesas_views.listar_reservas, name='listar_reservas'),
    path('reservas/crear/', mesas_views.crear_reserva, name='crear_reserva'),
    path('pedidos/', pedidos_views.gestionar_pedidos, name='gestionar_pedidos'),  # Añadido para pedidos
]

ProyectoRestaurante_templateHome/menu/urls.py
from django.urls import path
from .views import categories_view, meals_view, meal_detail_view

urlpatterns = [
    path('categorias/', categories_view, name='categories'),
    path('categorias/<str:category_name>/', meals_view, name='meals_by_category'),
    path('menus/<str:meal_id>/', meal_detail_view, name='meal_detail'),
]

ProyectoRestaurante_templateHome/mesas/models.py
from django.core.exceptions import ValidationError
from django.db import models
from enum import Enum

class EstadoReserva(Enum):
    CONFIRMADA = "CONFIRMADA"
    CANCELADA = "CANCELADA"
    FINALIZADA = "FINALIZADA"
    ENCURSO = "ENCURSO"


class Mesa(models.Model):
    codigo = models.CharField(max_length=50, unique=True, null=True)
    numero_asientos = models.PositiveIntegerField()
    ubicacion = models.CharField(max_length=100)

    def __str__(self):
        return f"Mesa {self.codigo} - Capacidad {self.numero_asientos}"


class Persona(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    cedula = models.CharField(max_length=10, unique=True)
    telefono = models.CharField(max_length=15, unique=True)


class Cliente(Persona):
    def __str__(self):
        return self.nombre

    def actualizar_informacion(self, nombre, email, telefono):
        self.nombre = nombre
        self.email = email
        self.telefono = telefono
        self.save()


class Reserva(models.Model):
    mesa = models.ForeignKey(Mesa, on_delete=models.CASCADE, related_name="reservas")
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, related_name="reservas", null=True)
    fecha = models.DateField(null=True)
    hora_inicio = models.TimeField(null=True)
    hora_fin = models.TimeField(null=True)

    def clean(self):
        # Validar si el horario de la reserva se solapa con otras reservas para la misma mesa en la misma fecha
        reservas_conflictivas = Reserva.objects.filter(
            mesa=self.mesa,
            fecha=self.fecha
        ).exclude(id=self.id)  # Excluir la reserva actual si ya existe

        for reserva in reservas_conflictivas:
            if self.hora_inicio < reserva.hora_fin and self.hora_fin > reserva.hora_inicio:
                raise ValidationError(f"La mesa {self.mesa.codigo} ya está reservada en ese horario.")

    def __str__(self):
        return f"Reserva de {self.cliente} - Mesa {self.mesa.codigo} - {self.fecha} {self.hora_inicio}-{self.hora_fin}"

ProyectoRestaurante_templateHome/mesas/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.models import User
from mesas.models import Mesa, Reserva

class MesaForm(forms.ModelForm):
    class Meta:
        model = Mesa
        fields = ['codigo', 'ubicacion', 'numero_asientos']

class RegistroClienteForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, label="Contraseña")
    confirmar_password = forms.CharField(widget=forms.PasswordInput, label="Confirmar Contraseña")
    nombre = forms.CharField(max_length=100, required=True)
    apellido = forms.CharField(max_length=100, required=True)
    cedula = forms.CharField(max_length=10, required=True)
    telefono = forms.CharField(max_length=15, required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirmar_password = cleaned_data.get("confirmar_password")

        if password != confirmar_password:
            raise forms.ValidationError("Las contraseñas no coinciden.")

        return cleaned_data


class ReservaForm(forms.ModelForm):
    class Meta:
        model = Reserva
        fields = ['mesa', 'cliente', 'fecha', 'hora_inicio', 'hora_fin']

    widgets = {
        'fecha': forms.DateInput(attrs={'type': 'date'}),  # Selector de fecha (calendario)
        'hora_inicio': forms.TimeInput(attrs={'type': 'time'}),  # Selector de hora (reloj)
        'hora_fin': forms.TimeInput(attrs={'type': 'time'}),  # Selector de hora (reloj)
    }

    def clean(self):
        cleaned_data = super().clean()
        mesa = cleaned_data.get("mesa")
        fecha = cleaned_data.get("fecha")
        hora_inicio = cleaned_data.get("hora_inicio")
        hora_fin = cleaned_data.get("hora_fin")

        # Validar que la hora de inicio sea antes que la hora de fin
        if hora_inicio >= hora_fin:
            raise forms.ValidationError("La hora de inicio debe ser antes que la hora de fin.")

        # Validar si ya existe una reserva para la misma mesa y hora
        reservas_conflictivas = Reserva.objects.filter(
            mesa=mesa,
            fecha=fecha
        ).exclude(id=self.instance.id)  # Excluir la reserva actual si ya existe

        for reserva in reservas_conflictivas:
            if hora_inicio < reserva.hora_fin and hora_fin > reserva.hora_inicio:
                raise forms.ValidationError(f"La mesa {mesa.codigo} ya está reservada en ese horario.")

        return cleaned_data


class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, required=True)
    last_name = forms.CharField(max_length=100, required=True)
    id_number = forms.CharField(max_length=20, required=True)  # Cédula
    phone = forms.CharField(max_length=15, required=True)  # Teléfono
    username = forms.CharField(max_length=150, required=True)  # Cambié email por username

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'id_number', 'phone', 'password1', 'password2')

ProyectoRestaurante_templateHome/mesas/views.py
from django.contrib.auth import authenticate, logout
from django.http import HttpResponse

from mesas.forms import CustomUserCreationForm
from django.shortcuts import render, get_object_or_404, redirect
from .forms import MesaForm
from .models import Mesa, Cliente
from django.contrib import messages
from django.contrib.auth import login
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, CreateView, DeleteView
from mesas.admin import Reserva
from .forms import ReservaForm
from django.http import HttpResponse

def homeAdmin(request):
    return render(request, 'Admin/homeAdmin.html')
def home(request):
    return render(request, 'user/home.html')

def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')  # ✅ Usando .get() para evitar KeyError
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            messages.success(request, f'Bienvenido, {user.username}!')
            return redirect('home')  # ✅ Redirige al home después de iniciar sesión
        else:
            messages.error(request, 'Credenciales incorrectas. Intenta de nuevo.')

    return render(request, 'user/login.html')

def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)  # Por si acaso necesita hacer más operaciones
            user.username = form.cleaned_data.get('username')
            user.first_name = form.cleaned_data.get('first_name')
            user.last_name = form.cleaned_data.get('last_name')
            user.id_number = form.cleaned_data.get('id_number')
            user.phone = form.cleaned_data.get('phone')
            user.save()  # Ahora guardamos el usuario completo

            # Guardar también al Usuario como un Cliente
            Cliente.objects.create(
                nombre=user.first_name,
                apellido=user.last_name,
                cedula=user.id_number,
                telefono=user.phone,

            )

            messages.success(request, f'Cuenta creada para {user.username}! Ahora puedes iniciar sesión.')
            return redirect('login')  # Redirige al login después de registrarse
        else:
            for msg in form.error_messages:
                messages.error(request, f'{msg}: {form.error_messages[msg]}')
    else:
        form = CustomUserCreationForm()
    return render(request, 'user/register.html', {'form': form})

def logout_view(request):  # ✅ Nueva vista para cerrar sesión
    logout(request)
    messages.success(request, "Sesión cerrada correctamente.")
    return redirect('login')

class listar_mesas(ListView):
    model = Mesa
    template_name = 'AdminIndividual/mesas/listar_mesas.html'
    context_object_name = 'mesas'
    paginate_by = 10

    def get_queryset(self):
        return Mesa.objects.all()

class edicion_mesas(UpdateView):
    model = Mesa
    form_class = MesaForm
    template_name = 'AdminIndividual/mesas/editar_mesas.html'
    success_url = reverse_lazy('listar_mesas')

    def form_valid(self, form):
        return super().form_valid(form)

class crear_mesa(CreateView):
    model = Mesa
    form_class = MesaForm
    template_name = 'AdminIndividual/mesas/crear_mesa.html'
    success_url = reverse_lazy('listar_mesas')

def eliminar_mesa(request, pk):
    mesa = get_object_or_404(Mesa, pk=pk)
    mesa.delete()
    return redirect('listar_mesas')

def listar_reservas(request):
    reservas = Reserva.objects.all().order_by('-fecha')
    return render(request, 'reservas/lista_reservas.html', {'reservas': reservas})

def crear_reserva(request):
    if request.method == 'POST':
        form = ReservaForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Reserva creado exitosamente.")
            return redirect('listar_reservas')  # Redirigir a una página de éxito
        else:
            messages.success(request, "Ingrese datos correctos")
            # Si el formulario no es válido, vuelve a mostrarlo con errores
            return render(request, 'reservas/crear_reserva.html', {'form': form})
    else:
        form = ReservaForm()
    return render(request, 'reservas/crear_reserva.html', {'form': form})

def reserva_exito(request):
    return HttpResponse("Reserva realizada con éxito!")

def eliminar_reserva(request, pk):
    reserva = get_object_or_404(Reserva, pk=pk)
    reserva.delete()
    return redirect('listar_reservas')

ProyectoRestaurante_templateHome/templates/AdminIndividual/mesas/crear_mesa.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pedidos - Restaurante Michu</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&family=Playfair+Display:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/pedidos.css' %}?v=1.0">
</head>
<body>
    <header>
        <div class="logo">
            <img src="{% static 'image/Logo.jpg.png' %}" alt="Logo Restaurante Michu">
            <span class="restaurant-name">Restaurante Michu</span>
        </div>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">INICIO</a></li>
                <li><a href="{% url 'gestionar_menu' %}">MENÚ</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'listar_reservas' %}">RESERVACIONES</a></li>
                    <li><a href="{% url 'estadistica' %}">ESTADISTICAS</a></li>
                    <li><a href="{% url 'listar_mesas' %}">MESAS</a></li>
                    <li><a href="{% url 'gestionar_pedidos' %}">PEDIDOS</a></li>
                    <li><a href="{% url 'convertir_divisa' %}">MONEDAS</a></li>
                    <li><a href="{% url 'logout' %}">CERRAR SESIÓN</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">INICIAR SESIÓN</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    
    <main>   
        <section class="hero">
            <img src="{% static 'image/mesas.jpg' %}" alt="Imagen de inicio" class="hero-image">

            <div class="form-container">
                <div class="form-column">
                    <h2>Crear una Mesa</h2>
                    <form method="POST">
                        {% csrf_token %}

                        <div class="form-group">
                            <label for="id_codigo">Cliente</label>
                            {{ form.codigo }}
                        </div>

                        <div class="form-group">
                            <label for="id_numero_asientos">Numero de Asientos</label>
                            {{ form.numero_asientos }}
                        </div>

                        <div class="form-group">
                            <label for="id_ubicacion">Ubicacion</label>
                            {{ form.ubicacion }}
                        </div>

                        <button type="submit" name="crear_mesa">Crear Mesa</button>
                        <a href="{% url 'listar_mesas' %}">
                        <button>VOLVER A MESAS</button>
                        </a>
                    </form>
                </div>
            </div>
        </section>
    </main>
</body>
</html>

ProyectoRestaurante_templateHome/templates/AdminIndividual/mesas/editar_mesas.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Inventario</title>
    <link rel="stylesheet" href="{% static 'css/pedidos.css' %}">
</head>
<body>
    <header>
        <div class="logo">
            <img src="{% static 'image/Logo.jpg.png' %}" alt="Logo Restaurante Michu">
            <span class="restaurant-name">Lista de mesas</span>
        </div>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">INICIO</a></li>
                <li><a href="{% url 'gestionar_menu' %}">MENÚ</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'listar_reservas' %}">RESERVACIONES</a></li>
                    <li><a href="{% url 'estadistica' %}">ESTADISTICAS</a></li>
                    <li><a href="{% url 'listar_mesas' %}">MESAS</a></li>
                    <li><a href="{% url 'gestionar_pedidos' %}">PEDIDOS</a></li>
                    <li><a href="{% url 'convertir_divisa' %}">MONEDAS</a></li>
                    <li><a href="{% url 'logout' %}">CERRAR SESIÓN</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">INICIAR SESIÓN</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>

    <main>
        <section class="hero">
            <img src="{% static 'image/mesas.jpg' %}" alt="Imagen de inicio" class="hero-image">

            <div class="form-container">
                <div class="form-column">
                    <h2>Crear una Mesa</h2>
                    <form method="POST">
                        {% csrf_token %}

                        <div class="form-group">
                            <label for="id_codigo">Cliente</label>
                            {{ form.codigo }}
                        </div>

                        <div class="form-group">
                            <label for="id_numero_asientos">Numero de Asientos</label>
                            {{ form.numero_asientos }}
                        </div>

                        <div class="form-group">
                            <label for="id_ubicacion">Ubicacion</label>
                            {{ form.ubicacion }}
                        </div>
                        <button type="submit" name="crear_mesa">Guardar Cambios</button>
                        <a href="{% url 'listar_mesas' %}">
                        <button>VOLVER A MESAS</button>
                        </a>
                    </form>
                </div>
            </div>
        </section>
    </main>
</body>
</html>

ProyectoRestaurante_templateHome/templates/AdminIndividual/mesas/listar_mesas.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Mesas</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&family=Playfair+Display:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/tablas.css' %}?v=2">
</head>
<body>
    <div class="banner"></div>
    <header>
        <div class="logo">
            <img src="{% static 'image/Logo.jpg.png' %}" alt="Logo Restaurante Michu">
            <span class="restaurant-name">Restaurante Michu</span>
        </div>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">INICIO</a></li>
                <li><a href="{% url 'gestionar_menu' %}">MENÚ</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'listar_reservas' %}">RESERVACIONES</a></li>
                    <li><a href="{% url 'estadistica' %}">ESTADISTICAS</a></li>
                    <li><a href="{% url 'listar_mesas' %}">MESAS</a></li>
                    <li><a href="{% url 'gestionar_pedidos' %}">PEDIDOS</a></li>
                    <li><a href="{% url 'convertir_divisa' %}">MONEDAS</a></li>
                    <li><a href="{% url 'logout' %}">CERRAR SESIÓN</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">INICIAR SESIÓN</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>

    <main>
        <section class="hero">
        <img src="{% static 'image/mesas.jpg' %}" alt="Imagen de Reservas" class="hero-image">
            <h1>Listado de Mesas</h1>
            <p>Consulta mesas del restaurante.</p>
            <div class="table-container">
            <table class="tabla-mesas">
                <thead>
                    <tr>
                        <th>Código</th>
                        <th>Ubicación</th>
                        <th>Número de Asientos</th>
                        <th>Edición</th>
                        <th>Descartar</th>
                    </tr>
                </thead>
                <tbody>
                    {% for mesa in mesas %}
                    <tr>
                        <td>{{ mesa.codigo }}</td>
                        <td>{{ mesa.ubicacion }}</td>
                        <td>{{ mesa.numero_asientos }}</td>
                        <td class="btn">
                            <div class="btn">
                                <a href="{% url 'editar_mesas' mesa.pk %}"><i class="fas fa-trash-alt"></i> Editar</a>
                            </div>
                        </td>
                        <td>
                            <div class="btn">
                                <a href="{% url 'eliminar_mesa' mesa.pk %}" onclick="return confirm('¿Estás seguro de eliminar esta mesa?');"><i class="fas fa-trash-alt"></i> Eliminar</a>
                            </div>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="5">No hay mesas registradas.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <a href="{% url 'crear_mesa' %}">
        <button>AGREGAR</button>
        </a>

    {% if inventarios.has_other_pages %}
    <div class="pagination">
        <span class="step-links">
            {% if mesas.has_previous %}
                <a href="?page=1">&laquo; Primero</a>
                <a href="?page={{ mesas.previous_page_number }}">Anterior</a>
            {% endif %}
            <span class="current">
                Página {{ mesas.number }} de {{ mesas.paginator.num_pages }}.
            </span>
            {% if mesas.has_next %}
                <a href="?page={{ mesas.next_page_number }}">Siguiente</a>
                <a href="?page={{ mesas.paginator.num_pages }}">Último &raquo;</a>
            {% endif %}
        </span>
    </div>
    {% endif %}   
</main>
</body>
</html>